config/routes.rb
Stories::Application.routes.draw do |map|
  resources :stories do
    member do
      get :more_info
      get :export
      get :export_done
    end
    collection do
      get :import
      get :info
      get :quit
      get :export
      get :export_done
      get :qpe
    end
  end

  root :to => "stories#index"
end

app/models/story.rb
class Story < ActiveRecord::Base
  acts_as_taggable

  validates_presence_of :title, :content

  before_save :update_autos, :if => lambda { |story| story.content_changed? }
  
  def nsf
    Nsf::Document.from_nsf(content)
  end

  def open
    increment!(:opens)
    update_attribute(:last_opened_at, DateTime.now)
  end

  def page_count
    wpp = (x = ENV["STORIES_WORDS_PER_PAGE"]) ? x.to_f : 250.0
    (word_count / wpp).ceil
  end

  STOPWORDS = File.read("#{Rails.root}/config/stopwords.txt").split("\n")

  def self.wfa(text, exclusion_text)
    text, exclusion_text = wfa_preprocess(text), wfa_preprocess(exclusion_text)

    exclusions = exclusion_text.split(/\s/)

    hash = Hash.new(1)
    text.split(/(?:\s|\u2026|\.\.\.)/).map do |word|
      word.strip.gsub(/^\W/, "").gsub(/\W$/, "").gsub(/'s$/, "")
    end.reject do |word|
      word.blank?
    end.each do |w|
      hash[w] += 1
    end
    hash.reject! { |k, v| STOPWORDS.include?(k.downcase) || exclusions.include?(k.downcase) }
    hash.to_a.sort_by { |(k, v)| v }.reverse.map { |(k, v)| k }[0..25]
  end

  private
  def self.wfa_preprocess(text)
    text.to_ascii.gsub(/^[^A-z]+/, '').gsub(/[^A-z]+$/, '').gsub(/'[Ss]$/, '')
  end

  def self.sort_key(title)
    title.gsub(/[^A-Za-z0-9]+/, '').downcase
  end

  def update_autos
    self.word_count = content.split(/\s+/).length
    self.byte_size = content.bytesize
    self.most_frequent_words = Story.wfa(self.content, self.title).join(" ")    
    self.sort_key = Story.sort_key(title)
  end

  public

  COMPRESSED_FILE_EXTS = %w(.zip)
  HTML_EXTS = %w(.htm .html)
  NSF_EXTS = %w(.txt)
  ORDINARY_FILE_EXTS = HTML_EXTS + NSF_EXTS
  VALID_EXTS = COMPRESSED_FILE_EXTS + ORDINARY_FILE_EXTS #Add rtf later

  #Iterate recursively over all files/dirs
  #If current item is a zip/rar/cbr/cbz file, pull out first image and store zip filename as manga name and zip filename as filename to load.
  #Else if current item is a dir, and it contains images but no directories, store the dir name as the manga name as well as the load filename.
  #Else skip/recurse into dir.
  #Do not call more than once at a time
  def self.import
    import_directory(Stories.import_dir)
    system("cd #{File.quote_name(Stories.import_dir)} && find . -depth -type d -empty -exec rmdir {} \\;")
  end
  
  def self.import_directory(dir)
    require 'fileutils'
    FileUtils.rm_rf(Dir.glob("#{File.quote_glob_name(dir)}/**/*_files"))
    
    #Requires GNU find 3.8 or above
    cmd = <<-CMD
cd #{File.quote_name(dir)} && find . \\( -type f \\( #{VALID_EXTS.map { |ext| "-iname '*#{ext}'" }.join(' -o ')} \\) \\)
CMD

    $stdout.puts #This makes it actually import; fuck knows why

    path_list = IO.popen(cmd) { |s| s.read }
    path_list = path_list.split("\n").map { |e| e.gsub(/^\.\//, '') }.reject { |e| e[0, 1] == '.' }

    path_list.each { |path| self.import_file("#{dir}/#{path}") }
  end

  def self.import_file(real_path)
    last_modified = File.mtime(real_path)

    book = nil

    begin
      if COMPRESSED_FILE_EXTS.include?(File.extname(real_path).downcase)
        data_from_compressed_file(real_path)
        return
      elsif ORDINARY_FILE_EXTS.include?(File.extname(real_path).downcase)
        book = data_from_ordinary_file(real_path)
      end
    rescue Exception => e
      ActionDispatch::ShowExceptions.new(Stories::Application.instance).send(:log_error, e)
      return
    end
    
    if book[:content].present?
      title = book[:title].gsub(/_/, ' ').gsub(/\A[ [:cntrl:]]+/, '').gsub(/[ [:cntrl:]]+\Z/, '')
      Story.create!(:title => title, :content => book[:content], :published_on => last_modified)
    end

    FileUtils.rm(real_path) if File.exists?(real_path)
  end

  def self.data_from_compressed_file(real_path)
    temp_dir = "#{Dir.tmpdir}/stories_#{SecureRandom.hex(10)}"
    Dir.mkdir(temp_dir)

    if File.extname(real_path).downcase == '.zip'
      system("unzip #{File.quote_name(real_path)} -d #{File.quote_name(temp_dir)}")
      import_directory(temp_dir)
      FileUtils.rm(real_path) if File.exists?(real_path)
    end
    #elsif RAR_EXTS.include?(File.extname(real_path))
    #  system("cd #{File.escape_name(destination_dir)} && unrar e #{File.escape_name(real_path)}")
    #end

    FileUtils.rm_rf(temp_dir)
  end
  
  def self.data_from_ordinary_file(real_path)
    text = File.read(real_path).to_utf8
    is_html = HTML_EXTS.include?(File.extname(real_path).downcase) || text.downcase.include?("<html>")
    
    doc = Nsf::Document.from(text, is_html ? "html" : "text")
    
    { :title => (doc.title || File.basename(real_path) || "Unknown title"), :content => doc.to_nsf }
  end

  def export_file(format)
    ff = export(format)
    File.open("#{Stories.export_dir}/#{ff.filename}", "w") do |f|
      f << ff.content
      f.flush
    end
  end

  def export(format)
    send("export_#{format}")
  end

  def export_html    
    out = <<-EOF
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>#{CGI.escapeHTML title}</title>
    <link href="shared/style.css" media="all" rel="stylesheet" type="text/css">
    <script src="shared/jquery.js" type="text/javascript"></script>
    <script src="shared/jquery.twoup.js" type="text/javascript"></script>
    <script src="shared/story.js" type="text/javascript"></script>
  </head>
  <body>
    <div id="wrapper">
      #{nsf.to_html}
    </div>
  </body>
</html>
EOF

    FutureFile.new("#{File.sanitize_name(title)}.html", out, (published_on ? published_on : created_at))
  end

  def export_text
    FutureFile.new("#{File.sanitize_name(title)}.txt", nsf.to_nsf, (published_on ? published_on : created_at))
  end

  def export_pdf
    FutureFile.new("#{File.sanitize_name(title)}.pdf", nsf.to_pdf, (published_on ? published_on : created_at))
  end

  def export_rtf
    FutureFile.new("#{File.sanitize_name(title)}.rtf", nsf.to_nsf, (published_on ? published_on : created_at))
  end

  CSV_HEADER = ["Title", "Content", "Most Frequent Words", "Tags", "Opens", "Word Count", "Byte Size", "Last Opened At", "Published On", "Created At", "Updated At"]
  def export_csv
    [title, nsf.to_nsf, most_frequent_words, tag_list, opens, word_count, byte_size, last_opened_at.to_s, published_on.to_s, created_at.to_s, updated_at.to_s]
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :pick_page_style

  def index
    _run_search

    @stories_count = @stories.count
    @stories = @stories.limit(250)
  end

  def new
    @story = Story.new
  end

  def create
    @page_id = "stories-new"

    _process_edit_content

    @story = Story.new(params[:story])

    if @story.save
      flash[:success] = "Story successfully created"
      redirect_to story_path(@story)
    else
      render :action => 'new'
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @page_id = "stories-edit"

    _process_edit_content

    @story = Story.find(params[:id])    
    if @story.update_attributes(params[:story])
      redirect_to story_path(@story)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  def show
    @story = Story.find(params[:id])
    @title = @story.title
    Thread.new do
      sleep 1
      @story.open
    end
  end

  def more_info
    @story = Story.find(params[:id])
    render :layout => 'secondary'
  end

  def export
    exported = []

    if params.key?(:mode) && params.key?(:format)
      if params[:mode] == 'multiple'
        _run_search
        exported = @stories.map { |s| s.export(params[:format]) }
      else
        @story = Story.find(params[:id])
        exported = [@story.export(params[:format])]
      end

      flash.now[:success] = "#{params[:format].upcase} export completed successfully."

      if params[:format] == 'csv'
        require 'csv'
        CSV.open("#{Stories.export_dir}/#{DateTime.now.to_s.gsub(' ', '_')}.csv", "w") do |csv|
          csv << Story::CSV_HEADER
          exported.each { |e| csv << e }
        end
      else
        if params[:download] == "true"
          if exported.length == 1
            send_data exported.first.content, :filename => exported.first.filename, :mimetype => exported.first.mimetype
            return
          else
            #Zip up the files and send the zip file
          end
        else
          exported.each do |e|
            extname = File.extname(e.filename)
            basename = File.basename(e.filename).chomp(extname)
            full_path = generate_unique_path(Stories.export_dir, basename, extname)
            File.open(full_path, "w", :external_encoding => e.content.encoding, :internal_encoding => nil) do |f|
              f << e.content
              f.flush
            end
            File.utime(e.mtime, e.mtime, full_path)
          end
        end
      end
    end

    @title = if params[:mode] == "multiple"
      params[:search] ? "Export all stories that contain \"#{params[:search]}\"" : "Export all stories"
    else
      story = Story.find(params[:id])
      "Export #{story.title}"
    end

    render :action => 'export'
  end

  def export_done
    render :action => 'export_done', :layout => 'secondary'
  end

  QPE_LENGTH = 150
  def qpe
    stories = (Story.order("opens DESC").limit(QPE_LENGTH) | Story.order("last_opened_at DESC").limit(QPE_LENGTH) | Story.order("word_count DESC").limit(QPE_LENGTH))
    stories.each do |s|
      e = s.export("html")
      File.open("#{Stories.export_dir}/#{e.filename}", "w") do |f|
        f << e.content
        f.flush
      end
    end
    flash[:success] = "Stories exported successfully."
    redirect_to "/"
  end


  

  

  def import
    #Thread.new do #Temporarily remopve threading as it seems to be causing import problems
      Story.import
      flash[:success] = "Import completed successfully."
      redirect_to :action => 'index'
    #end
  end

  def info
    if Story.count == 0
      render :text => 'No items yet'
    end

    @oldest_story = Story.order('published_on ASC').where('published_on IS NOT NULL').first
    @newest_story = Story.order('published_on DESC').where('published_on IS NOT NULL').first
    @longest_story = Story.order('word_count DESC').first
    @shortest_story = Story.order('word_count ASC').first
    @most_popular_story = Story.order('opens DESC').first
    @least_popular_story = Story.order('opens ASC').first
    @disk_usage = File.size(Stories::Application::DATABASE_PATH)
  end


  #TODO: Move someplace better
  def quit
    Process.kill("TERM", $$)
  end

  private
  def _process_edit_content
    if params[:story][:content]
      doc = Nsf::Document.from_text(params[:story][:content].gsub(/\r?\n/, "\n"))

      params[:story][:title] = doc.title
      params[:story][:content] = doc.to_nsf
    end
  end

  def _run_search
    params[:sort] ||= 'created_at'
    params[:sort_direction] ||= 'DESC'
    @stories = if !params[:search].blank?
      included_tags, excluded_tags = ActsAsTaggableOn::TagList.from(params[:search]).partition { |t| t.gsub!(/^-/, ''); $& != '-' }

      results = Story
      
      results = results.where("opens > 0") if included_tags.delete 's:read'
      results = results.where("opens = 0") if included_tags.delete 's:unread'
      #results = results.where("COUNT(taggings.id) > 0") if included_tags.delete 's:tagged'
      results = results.where("word_count >= 5000") if included_tags.delete 's:long'
      results = results.where("word_count <= 4999") if included_tags.delete 's:short'
      


      results = results.tagged_with(excluded_tags, :exclude => true) unless excluded_tags.empty?
      results = results.tagged_with(included_tags) unless included_tags.empty?

      c = Story.connection

      #This next part makes me want to become an hero
      search_inc = if included_tags.empty?
        nil
      else
        included_tags.map do |t|
          "(stories.title LIKE ? OR stories.most_frequent_words LIKE ?)".gsub("?", c.quote("%#{t}%"))
        end.join(" AND ")
      end
      search_ex = if excluded_tags.empty?
        nil
      else
        excluded_tags.map do |t|
          "(NOT (stories.title LIKE ? OR stories.most_frequent_words LIKE ?))".gsub("?", c.quote("%#{t}%"))
        end.join(" AND ")
      end
      
      results.where_values = ["(#{(results.where_values + [search_ex]).compact.map { |w| "(#{w})" }.join(" AND ")})" +
       (search_inc.nil? ? "" : " OR (#{search_inc})")]

      results
    else
      Story
    end.order("#{params[:sort]} #{params[:sort_direction]}")
  end

  private
  def pick_page_style
    @page_style = ([:new, :create, :edit, :update, :destroy, :export, :info].include?(action_name.to_sym) ? "manipulate" : "application")
  end

  def generate_unique_path(directory, basename, extname)
    suffix = 0
    full = ""
    loop do
      full = directory + "/" + basename + (suffix == 0 ? "" : " (#{suffix})") + extname
      break unless File.exist?(full)
      suffix += 1
    end
    full
  end
end

app/helpers/stories_helper.rb
# encoding: UTF-8
module StoriesHelper
  include ActsAsTaggableOn::TagsHelper

  def is_last_page?(collection)
    collection.total_pages == 0 || (collection.total_pages == (params[:page].blank? ? 1 : params[:page].to_i))
  end

  def stories_with(new_params)
    stories_path(params.except(:controller, :action, :page).merge(new_params))
  end

  def wbrize(str)
    str
    #str.split(' ').map { |sub_str| sub_str.split(/.{,30}/).join("<wbr>") }.join(' ')
  end

  def story_title(story)
    wbrize(story.title.gsub(/\s+/, ' '))
  end

  def story_title_classes(story)
    classes = ["title"]
    classes << if story.opens >= 10
      "many_opens"
    elsif story.opens < 3
      "unopened"
    elsif story.page_count <= 20
      "scrap"
    end
    classes.join(" ")
  end

  def ic(icon, text)
    "#{raw image_tag("icons/#{icon}.png")} <span>#{text}</span>".html_safe
  end

  def number_to_stars(num)
    return "" if num < 0

    case num
    when 0..1999
      "•"
    when 2000..4999
      "••"
    when 5000..9999
      "•••"
    else
      "••••"
    end
  end

  def show_toc?(story)
    story.nsf.toc.length > 1
  end

  def toc(story)
    headings = story.nsf.toc

    out = "<ul>"
    headings.each_with_index do |heading, i|
      p = i > 0 ? headings[i - 1].level : nil
      n = (x = headings[i + 1]) && x.level

      out << "<li><a href=\"##{CGI.escapeHTML(heading.ref_html)}\">#{CGI.escapeHTML(heading.text)}</a>"
      out << if n && heading.level < n
        "<ul>"
      elsif n && heading.level == n
        "</li>"
      else
        "</li></ul></li>"
      end
    end
    out << "</ul>"

    out.html_safe
  end

  def fd_piechart(div, title, keys, values)
    return raw <<-EOF
    <script type="text/javascript">
    $(function()
    {
      pieify('#{div}', "#{escape_javascript title}", #{keys.to_json}, #{values.to_json});
    })
    </script>
EOF
  end
    
end

app/views/stories/_end_of_results.html.erb
<li>
  <div class='last_page_message'>End of results.</div>
</li>

app/views/stories/_form.html.haml
= form_for @story do |f|
  - unless @story.errors.empty?
    %div.errors
      There were some errors:
      %ul
        - @story.errors.full_messages.each do |message|
          %li= message

  = f.text_area :content, :autofocus => "autofocus"

  = f.label :tag_list
  = f.text_field :tag_list
  .clear
  = f.submit
  .clear

app/views/stories/_nav.html.haml
- content_for :nav do
  %li= link_to(ic('accept', "Close"), "#", :onclick => 'window.close();')
  %li= link_to(ic('pencil_add', "Add a story"), new_story_path, :target => '_blank')
  %li= link_to(ic('add', "Import"), import_stories_path)
  %li= link_to(ic('package_go', "Export"), export_stories_path(params.except(:controller, :action).merge(:mode => 'multiple')), :id => 'stories_export', :target => '_blank')
  %li= link_to(ic("information", "Report"), info_stories_path)
  %li= link_to(ic('door_in', 'Quit'), quit_stories_path, :confirm => "Are you sure you want to quit the Story Reader?", :id => "off")

app/views/stories/_single_nav.html.haml
- content_for :nav do
  %li= link_to(ic('pencil', "Edit"), edit_story_path(@story))
  %li.separator
  %li= link_to(ic('page_white_world', "Download as HTML"), export_story_path(params.except(:controller, :action).merge(:mode => 'single', :format => 'html', :download => true)))
  %li= link_to(ic('page_white_acrobat', "Download as PDF"), export_story_path(params.except(:controller, :action).merge(:mode => 'single', :format => 'pdf', :download => true)))
  %li= link_to(ic('page_white_text', "Download as TXT"), export_story_path(params.except(:controller, :action).merge(:mode => 'single', :format => 'text', :download => true)))
  %li= link_to(ic('package_go', "Export"), export_story_path(params.except(:controller, :action).merge(:mode => 'single')), :id => 'story_export')
  %li.separator
  %li= link_to(ic('delete', "Delete"), story_path(@story), :method => :delete, :confirm => 'Are you sure?')
  %li= link_to(ic('accept', "Close"), "#", :onclick => 'window.close();')

app/views/stories/_story.html.haml
%li{ :id => dom_id(story) }
  = link_to(story, :target => '_blank') do
    %span{ :title => "Story title", :class => story_title_classes(story) }= story_title(story)
    %span.mfw{ :title => "Most frequent words in story" }= wbrize(story.most_frequent_words)
    - unless story.tag_list.empty?
      %span.tags{ :title => "Story tags" }= story.tag_list

    %span.opens{ :title => "Story view count" }= story.opens

    .emblems
      %span.wc{ :title => "Page count of story" }= number_with_delimiter(story.page_count)

app/views/stories/edit.html.haml
= render :partial => 'single_nav'
%h1 Edit story #{@story.title}
= render :partial => 'form'

app/views/stories/export.html.haml
- content_for :nav do
  %li= link_to(ic('accept', "Close"), "#", :onclick => 'window.close();')

%h1= @title
- url = params.except(:controller, :action).merge(:controller => 'stories', :action => 'export')
%p Export as:
%ul
  %li= link_to(ic("page_white_world", "HTML"), params.merge(:format => 'html'))
  %li= link_to(ic("page_white_text", "Text/NSF"), params.merge(:format => 'text'))
  %li= link_to(ic("page_white_acrobat", "PDF"), params.merge(:format => 'pdf'))
  %li= link_to(ic("page_white_word", "RTF"), params.merge(:format => 'rtf'))
  %li= link_to(ic("page_white_word", "CSV"), params.merge(:format => 'csv'))

- if params[:mode] == 'multiple'
  %p= link_to(ic("compress", "Compress results"), "#")

app/views/stories/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "story-index" %>  
<% end %>

<%= render :partial => 'nav' %>

<div id="header">
  <%= form_tag(stories_path, { :method => :get, :id => 'search_form' }) do %>
    <%= text_field_tag 'search', params[:search] %>
    <%= select_tag 'sort', options_for_select([['Published', 'published_on'], ['Alphabetically', 'sort_key'], ['Last opened at', 'last_opened_at'], ['Date added', 'created_at'], ['Popularity', 'opens'], ['Word count', 'word_count']], params[:sort]) %>
    <%= select_tag 'sort_direction', options_for_select([['Descending', 'DESC'], ['Ascending', 'ASC']], params[:sort_direction]) %>
    <%= link_to("Reset", stories_path) %>
  <% end %>
</div>

<div class="clear"></div>
<ul id="stories">
  <%= render :partial => 'story', :collection => @stories %>
  <% if @stories.empty? %>
    <li><div class="results">No results found.</div></li>
  <% elsif @stories_count > 100 %>
    <li><div class="results">There are more stories, restrict your search to see them.</div></li>
  <% end %>
</ul>
<div class="clear"></div>

app/views/stories/info.html.erb
<% content_for :head do %>
  <%= include_javascripts :graphs %>
<% end %>
<%= render :partial => 'nav' %>

<h1>Report on Your Collection of Stories</h1>

<p>You have <%= pluralize(number_with_delimiter(Story.count), 'story') %> and <%= pluralize(number_with_delimiter(ActsAsTaggableOn::Tag.count), 'tag') %>.</p>

<% unless Story.count.zero? %>
  <p>The oldest story was published on <%= link_to(@oldest_story.published_on, @oldest_story, :target => '_blank') %>
  and the newest story was published on <%= link_to(@newest_story.published_on, @newest_story, :target => '_blank') %>.</p>

  <div class="stats-wrapper">
    <div id="story_lengths" class="chart"></div>
    <%
    values = ActiveRecord::Base.connection.select_values("SELECT word_count FROM stories").map { |n| n.to_i.round_nearest(1000) }
    hash = Hash.new(0)
    values.each { |value| hash[value] += 1 }
    keys = hash.keys.sort.map { |v| "#{number_with_delimiter(v)} - #{number_with_delimiter(v + 999)}" }
    values = hash.keys.sort.map { |k| hash[k] }
    %>
    <%= fd_piechart("story_lengths", "Story length (word count)", keys, values) %>
    <div class="stats">
      <p>The longest story has <%= link_to(pluralize(number_with_delimiter(@longest_story.word_count), 'words'), @longest_story, :target => '_blank') %> and the
      shortest has <%= link_to(pluralize(number_with_delimiter(@shortest_story.word_count), 'words'), @shortest_story, :target => '_blank') %>, with an average
      of <%= pluralize(number_with_delimiter(Story.average('word_count'), :precision => 1), 'words') %>.</p>
    </div>
    <div class="clear"></div>
  </div>

  <p>The most popular story in your collection has been opened
  <%= link_to(pluralize(number_with_delimiter(@most_popular_story.opens), 'time'), @most_popular_story, :target => '_blank') %>,
  and the least popular opened <%= link_to(pluralize(number_with_delimiter(@least_popular_story.opens), 'time'), @least_popular_story, :target => '_blank') %>,
  with an average of <%= pluralize(number_with_precision(Story.average('opens'), :precision => 1), 'open') %> per story.</p>
  
  <p><%= link_to(pluralize(number_with_delimiter(Story.count(:conditions => 'opens > 0')), 'story has', 'stories have'), stories_with(:search => 's:read'), :target => "_blank") %>
    been opened at least once, and <%= link_to(pluralize(number_with_delimiter(Story.count(:conditions => 'opens = 0')), 'story has', 'stories have'), stories_with(:search => 's:unread'), :target => '_blank') %>
    never been opened at all.</p>

  <p>Your collection uses <%= number_to_human_size(@disk_usage) %> of disk space.</p>
<% end %>

<!-- add most and least popular tags -->

app/views/stories/more_info.html.erb
<div id="story">
  <div id="info">
    <span class="title"><%= h @story.title %></span><br>
    Opens <%= image_tag("icons/application_go.png", :title => "Opens") %>: <%= @story.opens %><br>
    Published: <%= @story.published_on %><br>
    Added: <%= @story.created_at %><br>
    Last Opened: <%= @story.last_opened_at || "Unknown" %><br>
    Tags: <%= raw @story.tag_counts.map { |tag| link_to tag.name, stories_path(params.except(:controller, :action).merge(:search => tag.name)), :title => pluralize(tag.taggings.count, "Occurence"), :target => "_top" }.join(' ') %>
    <%# tag.taggings is a hack, if we ever tag a different mofdel, will need to restrict to books. %>
    <div class="actions">
      <ul>
        <li><%= link_to("Open story", send("#{@story.type.downcase}_url", @story), :remote => true) %></li>
        <li><%= link_to("Search google for the title", "http://google.com/search?q=#{CGI::escape @story.title}", :target => "_blank") %></li>
      </ul>
    </div>
  </div>
</div>

app/views/stories/new.html.haml
= render :partial => 'nav'
%h1 Add a story
= render :partial => 'form'

app/views/stories/show.html.haml
= render :partial => 'single_nav'
- #- if show_toc?(@story)
- #  #toc
- #    %h3 Table of Contents
- #    = toc @story
= raw @story.nsf.to_html

app/views/stories/tags.html.haml
  <% tag_cloud(@tags, %w(size_1 size_2 size_3 size_4)) do |tag, css_class| %>
  <%= link_to tag.name, stories_path(params.except(:controller, :action).merge(:search => tag.name)), :class => css_class, :title => pluralize(tag.count, "Occurence") %>
  <% end %>